FROM node:10.12-alpine AS node

RUN apk update && apk add --no-cache --update make gcc g++ libc-dev libpng-dev automake autoconf libtool
RUN npm i webpack webpack-cli -g

WORKDIR /app
COPY package.json  /app/
COPY . /app/

RUN npm i -D && npm i -g webpack-dev-server
ENV NODE_ENV=development
ENV QILIN_API=https://qilinapi.tst.protocol.one
RUN webpack

CMD webpack-dev-server
EXPOSE 8080
