version: '3'
services:
  p1qilinfront:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: p1qilinfront
    networks:
    - p1devnet
    ports:
    - "8080:8080"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: unless-stopped

volumes:
  node_modules:

networks:
  p1devnet:
    external: true
